name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CSV_URL: "healthcare_cybersecurity_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Run MLflow training
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          uv run mlflow run . --experiment-name "Healthcare CVE Classification" --env-manager=local

      - name: Commit and push results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: automated mlflow run results [skip ci]"
          file_pattern: 'mlruns/*'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Latest Run ID
        id: get_run_id
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          export MLFLOW_TRACKING_URI=file:./mlruns
          RUN_ID=$(uv run python -c "import mlflow; print(mlflow.search_runs(experiment_names=['Healthcare CVE Classification']).iloc[0].run_id)")
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Build MLflow Model Image
        run: |
          uv run python -c "import mlflow.models; mlflow.models.build_docker(model_uri='runs:/${{ steps.get_run_id.outputs.run_id }}/model', name='tmp-model-image', install_mlflow=True, env_manager='local', base_image='python:3.12-slim')"

      - name: Tag Docker Image
        run: |
          docker tag tmp-model-image ${{ vars.DOCKERHUB_USERNAME }}/smsml_andi-irham:latest

      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/smsml_andi-irham:latest
